language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"

install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install --use-mirrors argparse unittest2; fi
  - pip install -r requirements_dev.txt --use-mirrors
  - git clone https://github.com/quantmind/pulsar.git
  - cd pulsar
  - git checkout -b dev origin/dev
  - python setup.py install
  - cd ..
  - sudo rm -rf pulsar
  - python setup.py install
  - sudo rm -rf /dev/shm && sudo ln -s /run/shm /dev/shm

services:
  - redis-server

script:
  - pep8 stdnet --exclude stdnet/apps/searchengine/processors
  - sudo rm -rf stdnet
  - python -m covrun

notifications:
  email: false

# Only test master and dev
branches:
  only:
    - master
    - dev
